// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
// eslint-disable-next-line import/no-extraneous-dependencies
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    ChangePasswordForm: typeof import('./src/components/ChangePasswordForm.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FormElement: typeof import('./src/components/FormElement.vue')['default']
    IconClosedEye: typeof import('./src/components/icons/IconClosedEye.vue')['default']
    IconEdit: typeof import('./src/components/icons/IconEdit.vue')['default']
    IconEye: typeof import('./src/components/icons/IconEye.vue')['default']
    IconTrashBin: typeof import('./src/components/icons/IconTrashBin.vue')['default']
    MultipleSelect: typeof import('./src/components/MultipleSelect.vue')['default']
    PasswordBlock: typeof import('./src/components/PasswordBlock.vue')['default']
    PersonalInformationForm: typeof import('./src/components/PersonalInformationForm.vue')['default']
    PhoneInput: typeof import('./src/components/PhoneInput.vue')['default']
    TheProfile: typeof import('./src/components/TheProfile.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
  }
}
